# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 283deba0ca6437afb175361dedad91c77f4f5c39d36dc968c02d8d637f1f0bb5a1356fe9b4aeabaafa6f4ed246bafa7baa04d00961bc6c95e3be2e27d6b70321

test:
  secret_key_base: b66cbfcd6059021045417707a6a8d043fcba0c0f90bf2194af19b07ad495ea6c4662a7ba98e7d848832dc46be62564e1b169ddc1867447e748d87ece6fe59f37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
